// Client.js: Handles server communications

// Reusable error handler
function handleServerUnreachable(error) {
  console.error("Critical error: " + error);
  return {successful: false, error: "Server unreachable"};
}

/* registrationRequest: sends registration form data to the server.
* Used to register a new account in the database. */
export async function registrationRequest(email, name, password) {
  try {
    // Create object containing all three fields
    const request = { email: email, name: name, password: password };
    
    // Send the POST request
    const response = await fetch(`/api/auth/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', },
      body: JSON.stringify(request)
    });

    if (!response) {
      return handleServerUnreachable("No response from server");
    }

    // Retrieve response
    const data = await response.json();

    if (!response.ok) {
      console.error("Server failed to create account:", response.status, data.error);
      return {successful: false, error: "Error creating account: " + String(data.error)};
    }

    console.log("Account created successfully! ", response.status, data);
    return {successful: true, error: null};

  } catch (error) {
      return handleServerUnreachable(error);
  }
}

/* loginRequest: sends login form data to the server. 
* When successful, returns an HTTP only cookie containing a JWT token. */
export async function loginRequest(emailOrName, password) {
  try {
    // Always set isEmail to true for now
    const request = { identifier: emailOrName, password: password, isEmail: true };
    
    // Send the POST request
    const response = await fetch(`/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', },
      credentials: 'include', // Required for cookies
      body: JSON.stringify(request)
    });

    if (!response) {
      return handleServerUnreachable("No response from server");
    }

    // Retrieve response
    const data = await response.json();

    // Authentication error
    if (!response.ok) {
      console.error("Failed to authenticate:", response.status, data.error);
      return {successful: false, error: String(data.error)};
    }

    // Authentication successful
    console.log("Login successful! ", response.status);
    return {successful: true, error: null};

  } catch (error) {
      return handleServerUnreachable(error);
  }
}

/* logout: Logs out of the app and returns to login page. 
* When successful, returns an HTTP only cookie containing a JWT token. */
export async function logoutRequest() {
  try {
    // Send the POST request
    const response = await fetch(`/api/auth/logout`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', },
      credentials: 'include', // Required for cookies
    });

    if (!response) {
      return handleServerUnreachable("No response from server");
    }

    // Retrieve response
    const data = await response.json();

    // Logout error
    if (!response.ok) {
      console.error("Failed to logout:", response.status, data.error);
      return {successful: false, error: String(data.error)};
    }

    // Logout successful
    console.log("Logout successful. ", response.status);
    return {successful: true, error: null};

  } catch (error) {
      return handleServerUnreachable(error);
  }
}

/* whoAmI: Sends the cookie (generated by the login function) to the server for validation.
If successful, relevant account data is returned and access is granted to the xhat page! */
export async function whoAmI() {
  try {
    const response = await fetch(`/api/auth/me`, {
      method: 'GET',
      headers: { 'Accept': 'application/json', },
      credentials: 'include', // Required for cookies
    });

    if (!response) {
      return handleServerUnreachable("No response from server");
    }

    const data = await response.json();

    if (response.status >= 400) {
      console.log("Failed to validate cookie:", response.status, data.error);
      return {successful: false, account: null};
    }

    console.log("Cookie validated");
    return {successful: true, account: data.account};

  } catch (error) {
      return handleServerUnreachable(error);
  }
}

// Test function
export async function testAPI() {
    // test API call
    const response = await fetch(`/api/test`, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response.json();
}